#!/usr/bin/env python3
"""Build public wedding pages from small, credential-free gallery records.

Only published records enter production. --preview renders drafts locally.
The same renderer serves every couple; videos stream from their Drive files.
"""
import argparse
import datetime as dt
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MARKER = '<!-- Generated by build_weddings.py; edit data/weddings instead. -->'
SLUG = re.compile(r'[a-z0-9]+(?:-[a-z0-9]+)*\Z')
DRIVE_ID = re.compile(r'[A-Za-z0-9_-]{15,150}\Z')


def esc(value):
    return html.escape(str(value), quote=True)


def validate(record):
    """Fail closed on unknown/private fields and unsafe paths before any writes."""
    expected = {'schema_version', 'slug', 'names', 'date', 'status', 'drive_folder_id', 'videos'}
    if set(record) != expected or record['schema_version'] != 1:
        raise ValueError('Invalid gallery schema or unknown fields')
    if not isinstance(record['slug'], str) or not SLUG.fullmatch(record['slug']):
        raise ValueError('Invalid gallery slug')
    if record['status'] not in ('draft', 'published'):
        raise ValueError('Status must be draft or published')
    if not isinstance(record['names'], str) or not 1 <= len(record['names']) <= 120:
        raise ValueError('Gallery names are required')
    dt.date.fromisoformat(record['date'])
    if not DRIVE_ID.fullmatch(record['drive_folder_id']):
        raise ValueError('Invalid Drive folder ID')
    if not isinstance(record['videos'], list) or not 1 <= len(record['videos']) <= 100:
        raise ValueError('A gallery needs 1–100 explicitly selected videos')
    seen, drive_seen = set(), set()
    for video in record['videos']:
        if set(video) != {'id', 'title', 'drive_id', 'format', 'description'}:
            raise ValueError('Invalid video schema or unknown fields')
        if not SLUG.fullmatch(video['id']) or video['id'] in seen:
            raise ValueError('Invalid or duplicate film ID')
        if not DRIVE_ID.fullmatch(video['drive_id']) or video['drive_id'] in drive_seen:
            raise ValueError('Invalid or duplicate Drive file ID')
        if video['format'] not in ('landscape', 'portrait'):
            raise ValueError('Invalid video format')
        if not isinstance(video['title'], str) or not 1 <= len(video['title']) <= 120:
            raise ValueError('Invalid film title')
        if not isinstance(video['description'], str) or len(video['description']) > 300:
            raise ValueError('Invalid film description')
        seen.add(video['id'])
        drive_seen.add(video['drive_id'])
    return record


def date_label(value):
    date = dt.date.fromisoformat(value)
    return f'{date:%B} {date.day}, {date.year}'


def shell(title, description, path, content, preview=False):
    # Full HTML makes deep links useful without depending on client-side routing.
    return f'''<!DOCTYPE html>
{MARKER}
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)} | Take One Visuals</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="https://takeonevisuals.com{esc(path)}">
{'<meta name="robots" content="noindex,nofollow">' if preview else ''}
<meta property="og:type" content="website"><meta property="og:site_name" content="Take One Visuals">
<meta property="og:title" content="{esc(title)} | Take One Visuals">
<meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="https://takeonevisuals.com{esc(path)}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,400&family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/weddings.css">
<script src="/weddings.js" defer></script>
</head><body class="wedding-page">
<a class="skip-link" href="#main">Skip to content</a>
<nav class="nav solid" aria-label="Main navigation"><a href="/" class="wordmark">Take One Visuals</a>
<div class="nav-links"><a href="/weddings/" class="active">Films</a><a href="/films.html">Highlights</a><a href="/#inquire" class="inquire-link">Inquire</a></div></nav>
<main id="main" class="wedding-shell">{content}</main>
<div class="wedding-shell"><footer class="collection-footer"><a class="wordmark" href="/">Take One Visuals</a><span>Wedding films. Yours to return to.</span><a class="text-link" href="/weddings/">All weddings ↗</a></footer></div>
</body></html>'''


def couple_page(record, preview=False):
    first = record['videos'][0]
    # Collections with a single delivered film use singular labels too.
    film_count = f"{len(record['videos'])} {'film' if len(record['videos']) == 1 else 'films'}"
    buttons = []
    for index, video in enumerate(record['videos']):
        buttons.append(f'''<li><button type="button" class="film-choice" data-film="{esc(video['id'])}" aria-current="{'true' if index == 0 else 'false'}" aria-controls="wedding-player">
<span class="film-number">{index + 1:02d}</span><span class="film-choice-text"><span class="film-title">{esc(video['title'])}</span></span><span class="play-mark" aria-hidden="true">▶</span></button></li>''')
    # Keep titles clean and omit external Drive links, as requested.
    # Escape JSON script delimiters too, not just the visible HTML text.
    payload = json.dumps({'names': record['names'], 'videos': record['videos']}, ensure_ascii=False).replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
    content = f'''
<header class="collection-header"><a class="back-link" href="/weddings/">← All weddings</a>
<div class="collection-heading"><div><p class="eyebrow">The wedding collection</p><h1>{esc(record['names']).replace('&amp;', '<em>&amp;</em>')}</h1></div>
<div class="collection-details"><time datetime="{record['date']}">{date_label(record['date'])}</time><p>{film_count} to return to</p></div></div></header>
<div class="cinema" aria-label="Wedding film player">
<div class="cinema-bar"><span>Now showing</span><span id="film-position">01 / {len(record['videos']):02d}</span></div>
<div class="screen{' is-portrait' if first['format'] == 'portrait' else ''}" id="screen"><iframe id="wedding-player" src="https://drive.google.com/file/d/{first['drive_id']}/preview" title="{esc(record['names'])}: {esc(first['title'])}" allow="autoplay; fullscreen; encrypted-media; picture-in-picture" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div>
<div class="now-playing"><div><h2 id="film-title">{esc(first['title'])}</h2></div></div></div>
<p id="player-status" class="sr-only" aria-live="polite"></p>
<section class="film-collection" aria-labelledby="collection-title"><div class="collection-label"><h2 id="collection-title">Their films</h2><span>{len(record['videos'])} in the collection</span></div><ol class="film-list">{''.join(buttons)}</ol>
<noscript><p>Enable JavaScript to switch between films.</p></noscript></section>
<script id="wedding-data" type="application/json">{payload}</script>'''
    return shell(record['names'] + ' | Wedding Films', f'The wedding films of {record["names"]}, {date_label(record["date"])}. Watch their wedding film collection.', f'/weddings/{record["slug"]}/', content, preview)


def archive_page(records, preview=False):
    cards = []
    for record in records:
        initials = ' & '.join(part.strip()[0] for part in record['names'].split('&') if part.strip())
        cards.append(f'''<article class="archive-item" data-search="{esc(record['names'].casefold() + ' ' + date_label(record['date']).casefold())}"><a class="wedding-card" href="/weddings/{record['slug']}/">
<div class="archive-cover"><span class="monogram" aria-hidden="true">{esc(initials)}</span><span class="cover-label"><span>{len(record['videos'])} {'film' if len(record['videos']) == 1 else 'films'}</span><span>View collection ↗</span></span></div>
<h2>{esc(record['names'])}</h2><p><time datetime="{record['date']}">{date_label(record['date'])}</time></p></a></article>''')
    content = f'''<header class="archive-header"><p class="eyebrow">The wedding archive</p><h1>Every story has a home.</h1><p>A place to return to the day. Find a couple and explore their wedding film collection.</p></header>
<div class="archive-controls"><div class="archive-search"><label for="wedding-search">Find a couple</label><input id="wedding-search" type="search" placeholder="Search names or year" autocomplete="off"></div><p class="archive-count" id="archive-count" aria-live="polite">{len(records)} {'wedding' if len(records) == 1 else 'weddings'}</p></div>
<div class="archive-grid">{''.join(cards)}</div><p class="archive-empty" id="archive-empty" {'hidden' if records else ''}>{'No weddings match your search.' if records else 'Wedding collections are coming soon.'}</p><button type="button" class="load-more" id="load-more" hidden>View more weddings</button>'''
    return shell('Wedding Collections', 'Explore wedding film collections from Take One Visuals. Find a couple and watch the films from their day.', '/weddings/', content, preview)


def build(root=ROOT, preview=False, check=False):
    records = []
    for path in sorted((root / 'data/weddings').glob('*.json')):
        record = validate(json.loads(path.read_text()))
        if path.stem != record['slug']:
            raise ValueError(f'{path.name}: filename must match slug')
        records.append(record)
    records.sort(key=lambda r: (r['date'], r['slug']), reverse=True)
    included = [r for r in records if preview or r['status'] == 'published']
    outputs = {root / 'weddings/index.html': archive_page(included, preview)}
    for record in included:
        outputs[root / 'weddings' / record['slug'] / 'index.html'] = couple_page(record, preview)
    # A separate sitemap avoids rewriting unrelated pages' modification dates.
    urls = ['/weddings/'] + [f'/weddings/{r["slug"]}/' for r in included]
    outputs[root / 'weddings/sitemap.xml'] = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + ''.join(f'  <url><loc>https://takeonevisuals.com{url}</loc></url>\n' for url in urls) + '</urlset>\n'
    stale = []
    for path, content in outputs.items():
        if not path.exists() or path.read_text() != content:
            stale.append(str(path.relative_to(root)))
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    # Remove only our generated pages for records withdrawn from publication.
    for path in (root / 'weddings').glob('*/index.html'):
        if path not in outputs and MARKER in path.read_text():
            stale.append(str(path.relative_to(root)))
            if not check:
                path.unlink()
    if check and stale:
        raise ValueError('Generated pages are stale; run build_weddings.py: ' + ', '.join(stale))
    return len(included)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--preview', action='store_true', help='Include drafts; local preview only')
    parser.add_argument('--check', action='store_true', help='Fail if generated output is stale')
    args = parser.parse_args()
    print(f'Validated {build(preview=args.preview, check=args.check)} wedding collection(s).')
