/* This gate controls the workspace experience; static published assets are public.
   Sensitive future client data must use server-enforced database/storage policies. */
(async()=>{const allowed=document.documentElement.dataset.tovRoles.split(',');try{const member=await tovMembership();if(!member||!allowed.includes(member.role)){location.replace('/studio/?next='+encodeURIComponent(location.pathname));return;}try{localStorage.setItem('tov-last-workspace',location.pathname);}catch{}document.documentElement.classList.remove('tov-checking');const bar=document.createElement('nav');bar.className='tov-nav';bar.setAttribute('aria-label','TOV tools');const brand=document.createElement('a');brand.className='tov-brand';brand.href='/cam-b/';brand.textContent='TAKE ONE VISUALS';bar.append(brand);const tabs=document.createElement('div');tabs.className='tov-tabs';for(const [label,url,roles] of [['Shotlist','/cam-b/',['owner','shooter']],['Editor','/editor-preview/',['owner','editor']]]){if(!roles.includes(member.role))continue;const link=document.createElement('a');link.href=url;link.textContent=label;if(location.pathname.startsWith(url))link.setAttribute('aria-current','page');tabs.append(link);}bar.append(tabs);const logout=document.createElement('button');logout.className='tov-account';logout.textContent='Log out';logout.onclick=async()=>{logout.disabled=true;const {error}=await tovAuth.auth.signOut({scope:'local'});if(error){logout.disabled=false;logout.textContent='Try logging out again';}};bar.append(logout);document.body.prepend(bar);tovAuth.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')location.replace('/studio/');});}catch{
 // A temporary network failure must not look like a lost device session.
 document.documentElement.classList.remove('tov-checking');
 const panel=document.createElement('main');panel.style.cssText='padding:32px;font:16px system-ui';
 const message=document.createElement('p');message.textContent='Unable to restore your TOV access. Your saved login has been kept.';
 const retry=document.createElement('button');retry.textContent='Try again';retry.onclick=()=>location.reload();
 panel.append(message,retry);document.body.replaceChildren(panel);
}})();
